// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Blog struct {
	ID     string    `json:"id"`
	Title  string    `json:"title"`
	Author string    `json:"author"`
	Date   time.Time `json:"date"`
	Body   string    `json:"body"`
}

type NewBlog struct {
	Title  string    `json:"title"`
	Author string    `json:"author"`
	Date   time.Time `json:"date"`
	Body   string    `json:"body"`
}
